### ISSUE TITLE
How does this Work? I'm pretty much confused

### ISSUE THREAD

**Issue by LuciAkirami** [benbrandt/text-splitter#101]
So here's the code that I have tried
```
from semantic_text_splitter import HuggingFaceTextSplitter
from tokenizers import Tokenizer

content = """\
In the bustling streets of Tokyo, amidst the neon-lit skyline, a group of passionate activists gather, advocating for \
renewable energy initiatives to combat climate change. Meanwhile, in the serene countryside of Provence, a master perfumer \
meticulously blends rare botanical essences to create a signature fragrance destined to captivate the senses of the elite. \
Across the vast expanses of the Antarctic, a team of intrepid scientists ventures into the icy wilderness, uncovering ancient \
fossils that offer tantalizing clues about Earth's prehistoric past. In a cozy café nestled in the heart of New York City, a \
struggling novelist finds solace in the rhythmic clatter of the typewriter, weaving tales of love and loss set against the backdrop of a bustling metropolis.\
"""

max_tokens = 50
tokenizer = Tokenizer.from_pretrained("bert-base-uncased")
splitter = HuggingFaceTextSplitter(tokenizer, trim_chunks=False)
chunks = splitter.chunks(content, max_tokens)

for i, chunk in enumerate(chunks):
    print(f"CHUNK {i+1}: ", chunk)
```
Here's the output
```
CHUNK 1:  In the bustling streets of Tokyo, amidst the neon-lit skyline, a group of passionate activists gather, advocating for renewable energy initiatives to combat climate change. 
CHUNK 2:  Meanwhile, in the serene countryside of Provence, a master perfumer meticulously blends rare botanical essences to create a signature fragrance destined to captivate the senses of the elite. 
CHUNK 3:  Across the vast expanses of the Antarctic, a team of intrepid scientists ventures into the icy wilderness, uncovering ancient fossils that offer tantalizing clues about Earth's prehistoric past. 
CHUNK 4:  In a cozy café nestled in the heart of New York City, a struggling novelist finds solace in the rhythmic clatter of the typewriter, weaving tales of love and loss set against the backdrop of a bustling metropolis.
```
This the output I'm expecting too.

But, when I change the max_tokens to 100, I get this as the output
```
CHUNK 1:  In the bustling streets of Tokyo, amidst the neon-lit skyline, a group of passionate activists gather, advocating for renewable energy initiatives to combat climate change. Meanwhile, in the serene countryside of Provence, a master perfumer meticulously blends rare botanical essences to create a signature fragrance destined to captivate the senses of the elite. 
CHUNK 2:  Across the vast expanses of the Antarctic, a team of intrepid scientists ventures into the icy wilderness, uncovering ancient fossils that offer tantalizing clues about Earth's prehistoric past. In a cozy café nestled in the heart of New York City, a struggling novelist finds solace in the rhythmic clatter of the typewriter, weaving tales of love and loss set against the backdrop of a bustling metropolis.
```
Why is it creating only two chunks? The sentence 1 and 2 are different right? Shouldn't it produce the same chunks as in the first code? Because the Chunk 1 contains two sentences that are not related to each other. Sames goes for Chunk 2

**Comment by benbrandt** [comment]
Perhaps you are expecting this to do semantic embeddings to find split points?
While it is an interesting approach, it isn't currently being used in this library. 

If you look at the readme, you can see the methodology. Basically it finds that splitting by sentences is the highest semantic level that can fit within the chunk size, and then fits as many sentences as possible into the given chunk size. 

The semantic level is solely determined by the semantic _structure_ of the text (characters, graphemes, words, sentences, increasing levels of newlines), but there is no model that compares the semantic _meaning_ of the text.

**Comment by LuciAkirami** [comment]
Ohk, I got confused. I thought it was converting the sentences into embeddings and then calculating the semantic score between sentences and putting them together if they are simlilar. So basically what this library is doing is its splitting the paragraph into sentences and fitting it as many sentences as it can within the chunk size, right??

**Comment by benbrandt** [comment]
Close yeah. Basically it tries for each chunk to find the biggest semantic level that will fit in the chunk size and pull as many of those in as possible. 

So really small chunks might do it by character or word, larger ones by sentence or paragraph. And this may change from chunk to chunk, as it optimizes these levels per chunk to maximize the space but still find a good stopping point. 

It is closest to the RecursiveTextSplitter in Langchain, but I personally think it is much better because it takes much more data into account for split points, and should be more performant since I'm not allocating as many strings (though tokenizer libraries do more of this than they need to...which I have to rely on for checking token counts)

**Comment by LuciAkirami** [comment]
Yah yah, it's a bit similar to the RecursiveTextSplitter but also different in its own way. Anyways thanks for the clarification, closing this issue

**Comment by benbrandt** [comment]
The more important question: is it useful to you as is? Or for your use case does the embedding approach perform better?

**Comment by LuciAkirami** [comment]
As is yah, I mean it will be better than the RecursiveTextSplitter so obviously it will be good. What i'm looking is a bit more beyond. Like grouping semantically similar sentences in a single chunk. So one way to do this is, split the corpus into sentences, then compare the neighbhouring sentences and if they have a high semantic similarity (a pre-determined threshold), then group the sentences, else don't group em and go on to comparing the similarity btw the next pair

**Comment by benbrandt** [comment]
Yeah makes sense. 

I want to finish up my in-progress markdown splitter, and then see if the same approach for that works well with code parsers. 

Then something using embeddings is next on the hypothetical roadmap, but it might be a little bit.

**Comment by LuciAkirami** [comment]
Cool. By the way I just came across this https://github.com/agamm/semantic-split/tree/main. This seems to split the data based on semantic similarity. But it does miss some features. Like we cannot decide the chunk size in tokens (though we can provide the maximum number of sentences that can be in a single chunk, but this will not be great if the sentences are too large or small). I'm thinking to alter this code and fit in the chunk size parameter

**Comment by benbrandt** [comment]
Yes I think since some embedding models also have small context windows, I feel it is not an easy problem to solve. I think I could adapt my library to adjust the algorithm to also optionally take embeddings into account while keeping these other factors in mind. 

But like I said, it won't be done this weekend 🙂

**Comment by LuciAkirami** [comment]
Yah sure take your time :)
