### ISSUE TITLE
Overlap the text chunk

### ISSUE THREAD

**Issue by Bryson14** [benbrandt/text-splitter#105]
**Is your feature request related to a problem? Please describe.**
Is there a way to specify text chunk overlap when splitting the text? Similar to [lang chains OverlapText param](https://js.langchain.com/docs/modules/data_connection/document_transformers/#get-started-with-text-splitters)?

**Describe the solution you'd like**

Have a optional parameter for overlap which would overlap each chunk by a number of tokens.

**Describe alternatives you've considered**

**Additional context**

**Comment by benbrandt** [comment]
@Bryson14 chunk overlap isn't currently supported. However, the reason they have in the docs for using it is to avoid strange break points, and this recursive method has many more semantic levels than the Langchain one, so ideally it is already finding a meaningful breakpoint. 

If you have examples where the chunk overlap would be helpful however, I'd be happy to take a look. 

It's not easy to come up with a method, and I haven't found a case where this is helpful yet, but I am always to update based on new use cases.

**Comment by Bryson14** [comment]
Oh that is good to know! It's good to know rust is coming in handy with better semantics and performance!

**Comment by benbrandt** [comment]
@Bryson14 looking into this some more, I think there is some validity to this, especially at smaller chunk sizes. Reopening so I can track that I want to support this.

**Comment by benbrandt** [comment]
Moving to #119

**Comment by benbrandt** [comment]
@Bryson14 sorry for the wait, but chunk overlapping is now supported as of [v0.12.2](https://github.com/benbrandt/text-splitter/releases/tag/v0.12.2)

Let me know how it works for you!
