### ISSUE TITLE
Any benchmarks?

### ISSUE THREAD

**Issue by andersfylling** [benbrandt/text-splitter#78]
I'm a little interested in this package as I don't want a ton of dependencies. However, while you comment on performance I'm not seeing benchmarks to checks runtime and the quality improvements of chunking. Do you have any data on this?

**Comment by benbrandt** [comment]
Hi @andersfylling I did some benchmarking of chunking entire books, you can see the results here: https://github.com/benbrandt/text-splitter/pull/71

But this is solely from the Rust side, I haven't benchmarked the python side. What sort of benchmarks are important for you in your use case?
