### ISSUE TITLE
Accept a callback for checking chunk length

### ISSUE THREAD

**Issue by andersfylling** [benbrandt/text-splitter#79]
**Is your feature request related to a problem? Please describe.**
I would like to provide a custom function to validate chunk size, that does not fit the current parameters.

**Describe the solution you'd like**
Instead of specifying number of characters, or a tokenizer, etc. I wish to specify a callback that can be executed whenever a chunk size check needs to happen. 

**Additional context**
This will probably hurt performance, but could be very handy.

```py
def custom_check(characters: str) -> int:
	return some_custom_check(characters)

splitter = RecursiveTextSplitter()
chunks = splitter.split("some data here", custom_check)
```

**Comment by benbrandt** [comment]
Thanks @andersfylling this totally makes sense. In the Rust crate you can easily do this by implementing the `ChunkSizer` trait, but there isn't a way to do this on the python side. 

As you said, this will probably have a performance hit, but definitely seems reasonable. I can look into how to achieve this with pyo3 (how I am getting bindings from Rust to Python) and release an update

**Comment by benbrandt** [comment]
@andersfylling I added this in the latest v0.5.1 release. Let me know if this works for you!
